version: '3'

services:

        #________________________________________#
        #|                                      |#
        #|                NGINX                 |#
        #|______________________________________|#

    nginx:
        build: ./requirements/nginx/
        ports:
            - 443:443
        volumes:
            - ./requirements/nginx/conf/:/etc/nginx/conf.d/:ro
            - ./requirements/wordpress/html:/var/www/html
        depends_on:
            - wordpress
        networks:
            - inception-network
        restart: always

        #________________________________________#
        #|                                      |#
        #|              WORDPRESS               |#
        #|______________________________________|#

    wordpress:
        image: wordpress:php7.3-fpm-alpine
        ports:
            - 9000:9000
        volumes:
            - ./requirements/wordpress/html:/var/www/html
              #env_file:
              #- .env
        environment:
            - WORDPRESS_DB_HOST=db:3306
            - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
        depends_on:
            - mariadb
        networks:
            - inception-network
        restart: always

        #________________________________________#
        #|                                      |#
        #|               MARIADB                |#
        #|______________________________________|#

    mariadb:
        build: ./requirements/mariadb
        ports:
            - 3306:3306
        volumes:
            - ./requirements/mariadb/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - inception-network
        restart: always
networks:
  inception-network:
    driver: bridge
