version: '3'

services:

        #________________________________________#
        #|                                      |#
        #|                NGINX                 |#
        #|______________________________________|#

    nginx:
        build: ./requirements/nginx/
        ports:
            - 80:80 
            - 443:443
        volumes:
            - ./requirements/nginx/conf/:/etc/nginx/conf.d/:ro
        restart: always

        #________________________________________#
        #|                                      |#
        #|               MARIADB                |#
        #|______________________________________|#

    mariadb:
        build: ./requirements/mariadb/
        ports:
            - 3306:3306
        volumes:
             - ./requirements/mariadb/data:/var/lib/mysql
        environment:
             MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
             MYSQL_ROOT_PASSWORD:   ${MARIADB_ROOT_PASSWORD}
             MYSQL_DATABASE:        ${DB_NAME}
             MYSQL_USER:            ${USER_NAME}
             DB_NAME:               $WP_DATABASE_NAME

             MYSQL_PASSWORD:        ${USER_PASSWORD}
        restart: always

        #________________________________________#
        #|                                      |#
        #|              WORDPRESS               |#
        #|______________________________________|#

    wordpress:
        image: wordpress:php7.3-fpm-alpine
        ports:
            - "9000:9000"
        volumes:
            - ./requirements/wordpress/html:/var/www/html
        depends_on:
            - mariadb
        environment:
            MYSQL_HOST:         ${MYSQL_HOST}
            WP_DATABASE_NAME:   ${WP_DATABASE_NAME}
            WP_DATABASE_USER:  ${WP_DATABASE_USER}
            WP_DATABASE_PASSWORD:  ${WP_DATABASE_PASSWORD}
            DOMAIN_NAME:      ${DOMAIN_NAME}
            WP_TITLE:         ${WP_TITLE}
            WP_ADMIN_USER:     ${WP_ADMIN_USER}
            WP_ADMIN_PASSWORD:     ${WP_ADMIN_PASSWORD}
            WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
            WP_USER:           ${WP_USER}
            WP_PASSWORD:           ${WP_PASSWORD}
            WP_EMAIL:         ${WP_EMAIL}

