version: '3'

services:

        #________________________________________#
        #|                                      |#
        #|                NGINX                 |#
        #|______________________________________|#

    nginx:
        build: ./requirements/nginx/
        ports:
            - 443:443
        volumes:
            - wp_data:/var/www/html
        depends_on:
            - wordpress
        networks:
            - front
        restart: always

        #________________________________________#
        #|                                      |#
        #|              WORDPRESS               |#
        #|______________________________________|#

    wordpress:
        build: ./requirements/wordpress
        volumes:
            - wp_data:/var/www/html
        env_file:
            - .env
        depends_on:
            - mariadb
        networks:
            - front
            - back
        restart: always

        #________________________________________#
        #|                                      |#
        #|               MARIADB                |#
        #|______________________________________|#

    mariadb:
        build: ./requirements/mariadb
        volumes:
            - db:/var/lib/mysql
        env_file:
            - .env
        networks:
            - back
        restart: always
        
        #-----------------------------------------#
        #           networks & volumes            #
        #-----------------------------------------#

networks:
    front:
        driver: bridge
    back:
        driver: bridge
volumes:
    wp_data:
        driver: local
        driver_opts:
            type: none
            device: /home/chajax/data/html
            o: bind
    db:
        driver: local
        driver_opts:
            type: none
            device: /home/chajax/data/mysql
            o: bind
