version: '3'

services:

        #________________________________________#
        #|                                      |#
        #|                NGINX                 |#
        #|______________________________________|#

    nginx:
        build: ./requirements/nginx/
        ports:
            - 443:443
        volumes:
            - /home/chajax/data/html:/var/www/html
            - ./requirements/nginx/conf/:/etc/nginx/conf.d/:ro
        depends_on:
            - wordpress
        networks:
            - front
        restart: always

        #________________________________________#
        #|                                      |#
        #|              WORDPRESS               |#
        #|______________________________________|#

    wordpress:
        image: wordpress:php7.3-fpm
        volumes:
            - /home/chajax/data/html:/var/www/html
        env_file:
            - .env
        depends_on:
            - mariadb
        networks:
            - front
            - back
        restart: always

        #________________________________________#
        #|                                      |#
        #|               MARIADB                |#
        #|______________________________________|#

    mariadb:
        #build: ./requirements/mariadb
        image: mariadb:latest
        volumes:
            - /home/chajax/data/mysql:/var/lib/mysql
        env_file:
            - .env
        networks:
            - back
networks:
  front:
    driver: bridge
  back:
    driver: bridge
