version: '3'

services:
    webserver:
        image: nginx
        volumes:
            - ./requirements/nginx/conf/:/etc/nginx/conf.d/:ro
            - ./certbot/www:/var/www/certbot/:ro
        ports:
            - 80:80 
            - 443:443
        restart: always

#    mysql:
#        image: mariadb
#        volumes:
#            - /home/chajax/data:/var/lib/mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: mysql_root_pass
#            MYSQL_DATABASE: DB_NAME
#            MYSQL_USER: USER_NAME
#            MYSQL_PASSWORD: USER_PASS
#            restart: always
